//! P0 command registry (static, frozen at M1B).
//!
//! This is the canonical in-code transcription of the two registries owned by the
//! development plan's interface documents:
//!   - `40-interfaces/41-cli.md`  (p0-command-registry)
//!   - `40-interfaces/42-cli-input-contract.md` (p0-input-registry / typed fields)
//!
//! The fields are `&'static str` so the whole registry can live in a single `static`
//! array (no runtime allocation) and be shared by both the CLI parser (command-key
//! validation) and the golden snapshot generator (schema transcription).

/// A single P0 command registry row.
pub(crate) struct Reg {
    pub command_key: &'static str,
    pub input_schema: &'static str,
    pub target_schema: &'static str,
    pub kind: &'static str,
    pub output_schema: &'static str,
    pub security_class: &'static str,
    pub wait_default: &'static str,
    pub wait_allowed: &'static str,
    /// Semicolon-separated typed field DSL, e.g. `name:BotName!@argv;...`.
    pub typed_fields: &'static str,
}

/// True if `key` is one of the 63 registered P0 command keys.
pub(crate) fn is_known_command(key: &str) -> bool {
    REGISTRY.iter().any(|r| r.command_key == key)
}

/// Number of registered commands (63).
pub(crate) fn command_count() -> usize {
    REGISTRY.len()
}

pub(crate) static REGISTRY: [Reg; 63] = [
    Reg { command_key: "runtime-start", input_schema: "in-runtime-start-v1", target_schema: "tgt-instance-bootstrap-v1", kind: "H", output_schema: "out-host-action-v1", security_class: "host-admin", wait_default: "applied", wait_allowed: "applied", typed_fields: "ready_at:ReadyAt?@local{process,storage,runtime,control}=control;timeout:Duration?@local" },
    Reg { command_key: "runtime-status", input_schema: "in-runtime-status-v1", target_schema: "tgt-instance-v1", kind: "H/Q", output_schema: "out-host-status-v1", security_class: "read", wait_default: "immediate", wait_allowed: "immediate", typed_fields: "" },
    Reg { command_key: "runtime-stop-graceful", input_schema: "in-runtime-stop-graceful-v1", target_schema: "tgt-runtime-current-v1", kind: "C", output_schema: "out-operation-v1", security_class: "host-admin", wait_default: "committed", wait_allowed: "accepted,committed", typed_fields: "reason:BoundedText?@argv" },
    Reg { command_key: "runtime-stop-host", input_schema: "in-runtime-stop-host-v1", target_schema: "tgt-runtime-generation-v1", kind: "H", output_schema: "out-host-action-v1", security_class: "host-admin", wait_default: "applied", wait_allowed: "applied", typed_fields: "host_stop:True!@argv;if_host_generation:HostGeneration?@argv;confirmation:Confirmation!@local" },
    Reg { command_key: "runtime-doctor", input_schema: "in-runtime-doctor-v1", target_schema: "tgt-instance-v1", kind: "H/Q", output_schema: "out-diagnostic-stream-v1", security_class: "read", wait_default: "immediate", wait_allowed: "immediate", typed_fields: "section:DoctorSection?@argv;page_size:PageSize?@argv;cursor:Cursor?@argv" },
    Reg { command_key: "version", input_schema: "in-version-v1", target_schema: "tgt-instance-optional-v1", kind: "Q", output_schema: "out-version-v1", security_class: "read", wait_default: "immediate", wait_allowed: "immediate", typed_fields: "" },
    Reg { command_key: "bot-create", input_schema: "in-bot-create-v1", target_schema: "tgt-instance-v1", kind: "C", output_schema: "out-operation-v1", security_class: "mutate", wait_default: "committed", wait_allowed: "accepted,committed", typed_fields: "name:BotName!@argv;brain_policy:PolicyRef?@argv;permission_policy:PolicyRef?@argv;resource_policy:PolicyRef?@argv;provider_policy:PolicyRef?@argv" },
    Reg { command_key: "bot-list", input_schema: "in-bot-list-v1", target_schema: "tgt-instance-v1", kind: "Q", output_schema: "out-bot-page-v1", security_class: "read", wait_default: "immediate", wait_allowed: "immediate", typed_fields: "page_size:PageSize?@argv;cursor:Cursor?@argv;all:Bool?@local" },
    Reg { command_key: "bot-show", input_schema: "in-bot-show-v1", target_schema: "tgt-bot-selector-v1", kind: "Q", output_schema: "out-bot-v1", security_class: "read", wait_default: "immediate", wait_allowed: "immediate", typed_fields: "bot:BotSelector!@argv{canonical-id-or-scoped-exact}" },
    Reg { command_key: "bot-activate", input_schema: "in-bot-activate-v1", target_schema: "tgt-bot-revision-v1", kind: "C", output_schema: "out-operation-v1", security_class: "mutate", wait_default: "committed", wait_allowed: "accepted,committed", typed_fields: "bot:BotSelector!@argv{canonical-id-or-scoped-exact};if_revision:Revision?@argv" },
    Reg { command_key: "bot-deactivate", input_schema: "in-bot-deactivate-v1", target_schema: "tgt-bot-revision-v1", kind: "C", output_schema: "out-operation-v1", security_class: "mutate", wait_default: "committed", wait_allowed: "accepted,committed", typed_fields: "bot:BotSelector!@argv{canonical-id-or-scoped-exact};if_revision:Revision?@argv" },
    Reg { command_key: "bot-archive", input_schema: "in-bot-archive-v1", target_schema: "tgt-bot-revision-v1", kind: "C", output_schema: "out-operation-v1", security_class: "destructive", wait_default: "committed", wait_allowed: "accepted,committed", typed_fields: "bot:BotSelector!@argv{canonical-id-or-scoped-exact};if_revision:Revision?@argv;confirmation:Confirmation!@local" },
    Reg { command_key: "bot-restore", input_schema: "in-bot-restore-v1", target_schema: "tgt-bot-revision-v1", kind: "C", output_schema: "out-operation-v1", security_class: "mutate", wait_default: "committed", wait_allowed: "accepted,committed", typed_fields: "bot:BotSelector!@argv{canonical-id-or-scoped-exact};if_revision:Revision?@argv" },
    Reg { command_key: "conversation-show", input_schema: "in-conversation-show-v1", target_schema: "tgt-conversation-selector-v1", kind: "Q", output_schema: "out-conversation-v1", security_class: "read", wait_default: "immediate", wait_allowed: "immediate", typed_fields: "conversation:ConversationSelector!@argv{conversation-id-or-bot-main}" },
    Reg { command_key: "conversation-send", input_schema: "in-conversation-send-v1", target_schema: "tgt-conversation-revision-v1", kind: "C", output_schema: "out-operation-v1", security_class: "mutate", wait_default: "committed", wait_allowed: "accepted,committed", typed_fields: "conversation:ConversationSelector!@argv{conversation-id-or-bot-main};if_revision:Revision?@argv;content:ContentSource!@oneof{text,input-file,stdin,artifact-ref}" },
    Reg { command_key: "conversation-history", input_schema: "in-conversation-history-v1", target_schema: "tgt-conversation-v1", kind: "Q", output_schema: "out-message-page-v1", security_class: "read", wait_default: "immediate", wait_allowed: "immediate", typed_fields: "conversation:ConversationSelector!@argv{conversation-id-or-bot-main};page_size:PageSize?@argv;cursor:Cursor?@argv;all:Bool?@local;output:SafeOutputPath?@local" },
    Reg { command_key: "thread-create", input_schema: "in-thread-create-v1", target_schema: "tgt-conversation-revision-v1", kind: "C", output_schema: "out-operation-v1", security_class: "mutate", wait_default: "committed", wait_allowed: "accepted,committed", typed_fields: "conversation:ConversationSelector!@argv{conversation-id-or-bot-main};if_revision:Revision?@argv;title:ThreadTitle?@argv" },
    Reg { command_key: "thread-list", input_schema: "in-thread-list-v1", target_schema: "tgt-conversation-v1", kind: "Q", output_schema: "out-thread-page-v1", security_class: "read", wait_default: "immediate", wait_allowed: "immediate", typed_fields: "conversation:ConversationSelector!@argv{conversation-id-or-bot-main};page_size:PageSize?@argv;cursor:Cursor?@argv;all:Bool?@local" },
    Reg { command_key: "thread-show", input_schema: "in-thread-show-v1", target_schema: "tgt-thread-parent-v1", kind: "Q", output_schema: "out-thread-v1", security_class: "read", wait_default: "immediate", wait_allowed: "immediate", typed_fields: "thread:ThreadSelector!@argv{canonical-id-or-scoped-exact}" },
    Reg { command_key: "thread-send", input_schema: "in-thread-send-v1", target_schema: "tgt-thread-revision-v1", kind: "C", output_schema: "out-operation-v1", security_class: "mutate", wait_default: "committed", wait_allowed: "accepted,committed", typed_fields: "thread:ThreadSelector!@argv{canonical-id-or-scoped-exact};if_revision:Revision?@argv;content:ContentSource!@oneof{text,input-file,stdin,artifact-ref}" },
    Reg { command_key: "thread-history", input_schema: "in-thread-history-v1", target_schema: "tgt-thread-parent-v1", kind: "Q", output_schema: "out-message-page-v1", security_class: "read", wait_default: "immediate", wait_allowed: "immediate", typed_fields: "thread:ThreadSelector!@argv{canonical-id-or-scoped-exact};page_size:PageSize?@argv;cursor:Cursor?@argv;all:Bool?@local;output:SafeOutputPath?@local" },
    Reg { command_key: "thread-branch", input_schema: "in-thread-branch-v1", target_schema: "tgt-thread-revision-v1", kind: "C", output_schema: "out-operation-v1", security_class: "mutate", wait_default: "committed", wait_allowed: "accepted,committed", typed_fields: "thread:ThreadSelector!@argv{canonical-id-or-scoped-exact};if_source_revision:Revision?@argv;message_id:MessageId!@argv;title:ThreadTitle?@argv" },
    Reg { command_key: "task-submit", input_schema: "in-task-submit-v1", target_schema: "tgt-task-owner-revision-v1", kind: "C", output_schema: "out-operation-v1", security_class: "mutate", wait_default: "committed", wait_allowed: "accepted,committed", typed_fields: "owner:ScopeSelector!@argv{bot-project-or-channel};if_scope_revision:Revision?@argv;intent:ContentSource!@oneof{text,input-file,stdin,artifact-ref};delegate_to_bot:BotSelector?@argv;requested_sender_bot:BotSelector?@argv{operator-request-only};deadline:Deadline?@argv;budget:BudgetRef?@argv" },
    Reg { command_key: "task-list", input_schema: "in-task-list-v1", target_schema: "tgt-scope-v1", kind: "Q", output_schema: "out-task-page-v1", security_class: "read", wait_default: "immediate", wait_allowed: "immediate", typed_fields: "scope:ScopeSelector!@argv{bot-project-or-channel};state:TaskState?@argv;page_size:PageSize?@argv;cursor:Cursor?@argv;all:Bool?@local" },
    Reg { command_key: "task-show", input_schema: "in-task-show-v1", target_schema: "tgt-task-selector-v1", kind: "Q", output_schema: "out-task-v1", security_class: "read", wait_default: "immediate", wait_allowed: "immediate", typed_fields: "task:TaskSelector!@argv{canonical-id-or-scoped-exact}" },
    Reg { command_key: "task-watch", input_schema: "in-task-watch-v1", target_schema: "tgt-task-v1", kind: "S", output_schema: "out-task-stream-v1", security_class: "read", wait_default: "follow", wait_allowed: "follow", typed_fields: "task:TaskSelector!@argv{canonical-id-or-scoped-exact};cursor:Cursor?@argv" },
    Reg { command_key: "task-cancel", input_schema: "in-task-cancel-v1", target_schema: "tgt-task-generation-v1", kind: "C", output_schema: "out-operation-v1", security_class: "destructive", wait_default: "committed", wait_allowed: "accepted,committed,applied", typed_fields: "task:TaskSelector!@argv{canonical-id-or-scoped-exact};if_revision:Revision?@argv;if_execution_generation:Generation?@argv;reason:BoundedText?@argv" },
    Reg { command_key: "task-suspend", input_schema: "in-task-suspend-v1", target_schema: "tgt-task-generation-v1", kind: "C", output_schema: "out-operation-v1", security_class: "mutate", wait_default: "committed", wait_allowed: "accepted,committed,applied", typed_fields: "task:TaskSelector!@argv{canonical-id-or-scoped-exact};if_revision:Revision?@argv;if_execution_generation:Generation?@argv;reason:BoundedText?@argv" },
    Reg { command_key: "task-resume", input_schema: "in-task-resume-v1", target_schema: "tgt-task-revision-v1", kind: "C", output_schema: "out-operation-v1", security_class: "mutate", wait_default: "committed", wait_allowed: "accepted,committed,applied", typed_fields: "task:TaskSelector!@argv{canonical-id-or-scoped-exact};if_revision:Revision?@argv" },
    Reg { command_key: "task-redirect", input_schema: "in-task-redirect-v1", target_schema: "tgt-task-revision-v1", kind: "C", output_schema: "out-operation-v1", security_class: "destructive", wait_default: "committed", wait_allowed: "accepted,committed,applied", typed_fields: "task:TaskSelector!@argv{canonical-id-or-scoped-exact};if_revision:Revision?@argv;replacement:ContentSource!@oneof{text,input-file,stdin,artifact-ref}" },
    Reg { command_key: "task-result", input_schema: "in-task-result-v1", target_schema: "tgt-task-v1", kind: "Q", output_schema: "out-task-result-v1", security_class: "read", wait_default: "immediate", wait_allowed: "immediate", typed_fields: "task:TaskSelector!@argv{canonical-id-or-scoped-exact};artifact_id:ArtifactId?@argv;output:SafeOutputPath?@local" },
    Reg { command_key: "memory-get", input_schema: "in-memory-get-v1", target_schema: "tgt-memory-v1", kind: "Q", output_schema: "out-memory-v1", security_class: "read", wait_default: "immediate", wait_allowed: "immediate", typed_fields: "memory:MemorySelector!@argv{canonical-id-or-scoped-exact};scope:MemoryScopeSelector?@argv" },
    Reg { command_key: "memory-search", input_schema: "in-memory-search-v1", target_schema: "tgt-memory-scope-v1", kind: "Q", output_schema: "out-memory-page-v1", security_class: "read", wait_default: "immediate", wait_allowed: "immediate", typed_fields: "scope:MemoryScopeSelector!@argv;query:BoundedText!@argv;page_size:PageSize?@argv;cursor:Cursor?@argv;all:Bool?@local" },
    Reg { command_key: "memory-history", input_schema: "in-memory-history-v1", target_schema: "tgt-memory-v1", kind: "Q", output_schema: "out-memory-history-v1", security_class: "read", wait_default: "immediate", wait_allowed: "immediate", typed_fields: "memory:MemorySelector!@argv{canonical-id-or-scoped-exact};page_size:PageSize?@argv;cursor:Cursor?@argv" },
    Reg { command_key: "memory-propose", input_schema: "in-memory-propose-v1", target_schema: "tgt-memory-scope-revision-v1", kind: "C", output_schema: "out-operation-v1", security_class: "mutate", wait_default: "committed", wait_allowed: "accepted,committed", typed_fields: "scope:MemoryScopeSelector!@argv;if_scope_revision:Revision?@argv;statement:ContentSource!@oneof{text,input-file,stdin,artifact-ref};evidence:EvidenceRef*@argv" },
    Reg { command_key: "memory-promote", input_schema: "in-memory-promote-v1", target_schema: "tgt-memory-promotion-v1", kind: "C", output_schema: "out-operation-v1", security_class: "high-risk", wait_default: "committed", wait_allowed: "accepted,committed", typed_fields: "proposal:MemorySelector!@argv{canonical-id-or-scoped-exact};if_proposal_revision:Revision?@argv;target_scope:MemoryScopeSelector!@argv;if_target_scope_revision:Revision?@argv;evidence:EvidenceRef+@argv;declassification_ref:DecisionRef?@argv" },
    Reg { command_key: "project-create", input_schema: "in-project-create-v1", target_schema: "tgt-instance-v1", kind: "C", output_schema: "out-operation-v1", security_class: "mutate", wait_default: "committed", wait_allowed: "accepted,committed", typed_fields: "name:ProjectName!@argv;owner_bot:BotSelector!@argv{canonical-id-or-scoped-exact}" },
    Reg { command_key: "project-list", input_schema: "in-project-list-v1", target_schema: "tgt-instance-v1", kind: "Q", output_schema: "out-project-page-v1", security_class: "read", wait_default: "immediate", wait_allowed: "immediate", typed_fields: "page_size:PageSize?@argv;cursor:Cursor?@argv;all:Bool?@local" },
    Reg { command_key: "project-show", input_schema: "in-project-show-v1", target_schema: "tgt-project-selector-v1", kind: "Q", output_schema: "out-project-v1", security_class: "read", wait_default: "immediate", wait_allowed: "immediate", typed_fields: "project:ProjectSelector!@argv{canonical-id-or-visible-exact}" },
    Reg { command_key: "project-archive", input_schema: "in-project-archive-v1", target_schema: "tgt-project-revision-v1", kind: "C", output_schema: "out-operation-v1", security_class: "destructive", wait_default: "committed", wait_allowed: "accepted,committed", typed_fields: "project:ProjectSelector!@argv{canonical-id-or-visible-exact};if_revision:Revision?@argv;confirmation:Confirmation!@local" },
    Reg { command_key: "project-restore", input_schema: "in-project-restore-v1", target_schema: "tgt-project-revision-v1", kind: "C", output_schema: "out-operation-v1", security_class: "mutate", wait_default: "committed", wait_allowed: "accepted,committed", typed_fields: "project:ProjectSelector!@argv{canonical-id-or-visible-exact};if_revision:Revision?@argv" },
    Reg { command_key: "project-member-set", input_schema: "in-project-member-set-v1", target_schema: "tgt-project-membership-v1", kind: "C", output_schema: "out-operation-v1", security_class: "high-risk", wait_default: "committed", wait_allowed: "accepted,committed", typed_fields: "project:ProjectSelector!@argv{canonical-id-or-visible-exact};if_project_revision:Revision?@argv;member_bot:BotSelector!@argv{canonical-id-or-scoped-exact};role_ref:RoleRef!@argv;if_membership_generation:GenerationOrAbsent?@argv" },
    Reg { command_key: "project-member-remove", input_schema: "in-project-member-remove-v1", target_schema: "tgt-project-membership-v1", kind: "C", output_schema: "out-operation-v1", security_class: "high-risk", wait_default: "committed", wait_allowed: "accepted,committed", typed_fields: "project:ProjectSelector!@argv{canonical-id-or-visible-exact};if_project_revision:Revision?@argv;member_bot:BotSelector!@argv{canonical-id-or-scoped-exact};if_membership_generation:Generation?@argv" },
    Reg { command_key: "project-member-list", input_schema: "in-project-member-list-v1", target_schema: "tgt-project-v1", kind: "Q", output_schema: "out-membership-page-v1", security_class: "read", wait_default: "immediate", wait_allowed: "immediate", typed_fields: "project:ProjectSelector!@argv{canonical-id-or-visible-exact};page_size:PageSize?@argv;cursor:Cursor?@argv;all:Bool?@local" },
    Reg { command_key: "channel-create", input_schema: "in-channel-create-v1", target_schema: "tgt-project-revision-v1", kind: "C", output_schema: "out-operation-v1", security_class: "mutate", wait_default: "committed", wait_allowed: "accepted,committed", typed_fields: "project:ProjectSelector!@argv{canonical-id-or-visible-exact};if_project_revision:Revision?@argv;name:ChannelName!@argv" },
    Reg { command_key: "channel-list", input_schema: "in-channel-list-v1", target_schema: "tgt-project-v1", kind: "Q", output_schema: "out-channel-page-v1", security_class: "read", wait_default: "immediate", wait_allowed: "immediate", typed_fields: "project:ProjectSelector!@argv{canonical-id-or-visible-exact};page_size:PageSize?@argv;cursor:Cursor?@argv;all:Bool?@local" },
    Reg { command_key: "channel-show", input_schema: "in-channel-show-v1", target_schema: "tgt-channel-project-v1", kind: "Q", output_schema: "out-channel-v1", security_class: "read", wait_default: "immediate", wait_allowed: "immediate", typed_fields: "channel:ChannelSelector!@argv{canonical-id-or-project-exact}" },
    Reg { command_key: "channel-member-set", input_schema: "in-channel-member-set-v1", target_schema: "tgt-channel-membership-v1", kind: "C", output_schema: "out-operation-v1", security_class: "high-risk", wait_default: "committed", wait_allowed: "accepted,committed", typed_fields: "channel:ChannelSelector!@argv{canonical-id-or-project-exact};if_channel_revision:Revision?@argv;member_bot:BotSelector!@argv{canonical-id-or-scoped-exact};role_ref:RoleRef!@argv;if_membership_generation:GenerationOrAbsent?@argv" },
    Reg { command_key: "channel-member-remove", input_schema: "in-channel-member-remove-v1", target_schema: "tgt-channel-membership-v1", kind: "C", output_schema: "out-operation-v1", security_class: "high-risk", wait_default: "committed", wait_allowed: "accepted,committed", typed_fields: "channel:ChannelSelector!@argv{canonical-id-or-project-exact};if_channel_revision:Revision?@argv;member_bot:BotSelector!@argv{canonical-id-or-scoped-exact};if_membership_generation:Generation?@argv" },
    Reg { command_key: "channel-member-list", input_schema: "in-channel-member-list-v1", target_schema: "tgt-channel-v1", kind: "Q", output_schema: "out-membership-page-v1", security_class: "read", wait_default: "immediate", wait_allowed: "immediate", typed_fields: "channel:ChannelSelector!@argv{canonical-id-or-project-exact};page_size:PageSize?@argv;cursor:Cursor?@argv;all:Bool?@local" },
    Reg { command_key: "channel-send", input_schema: "in-channel-send-v1", target_schema: "tgt-conversation-revision-v1", kind: "C", output_schema: "out-operation-v1", security_class: "high-risk", wait_default: "committed", wait_allowed: "accepted,committed", typed_fields: "channel:ChannelSelector!@argv{canonical-id-or-project-exact};if_revision:Revision?@argv;content:ContentSource!@oneof{text,input-file,stdin,artifact-ref}" },
    Reg { command_key: "channel-history", input_schema: "in-channel-history-v1", target_schema: "tgt-conversation-v1", kind: "Q", output_schema: "out-message-page-v1", security_class: "read", wait_default: "immediate", wait_allowed: "immediate", typed_fields: "channel:ChannelSelector!@argv{canonical-id-or-project-exact};page_size:PageSize?@argv;cursor:Cursor?@argv;all:Bool?@local;output:SafeOutputPath?@local" },
    Reg { command_key: "process-show", input_schema: "in-process-show-v1", target_schema: "tgt-process-v1", kind: "Q", output_schema: "out-process-v1", security_class: "read", wait_default: "immediate", wait_allowed: "immediate", typed_fields: "process:ProcessSelector!@argv{canonical-id-or-scoped-exact}" },
    Reg { command_key: "process-watch", input_schema: "in-process-watch-v1", target_schema: "tgt-process-v1", kind: "S", output_schema: "out-process-stream-v1", security_class: "read", wait_default: "follow", wait_allowed: "follow", typed_fields: "process:ProcessSelector!@argv{canonical-id-or-scoped-exact};cursor:Cursor?@argv" },
    Reg { command_key: "operation-show", input_schema: "in-operation-show-v1", target_schema: "tgt-operation-key-v1", kind: "Q", output_schema: "out-receipt-v1", security_class: "recovery", wait_default: "immediate", wait_allowed: "immediate", typed_fields: "operation:OperationSelector!@argv{operation-command-or-idempotency}" },
    Reg { command_key: "operation-reconcile", input_schema: "in-operation-reconcile-v1", target_schema: "tgt-operation-revision-v1", kind: "C", output_schema: "out-operation-v1", security_class: "recovery", wait_default: "committed", wait_allowed: "accepted,committed", typed_fields: "operation:OperationSelector!@argv{operation-command-or-idempotency};if_receipt_revision:Revision?@argv" },
    Reg { command_key: "approval-list", input_schema: "in-approval-list-v1", target_schema: "tgt-principal-scope-v1", kind: "Q", output_schema: "out-approval-page-v1", security_class: "read", wait_default: "immediate", wait_allowed: "immediate", typed_fields: "scope:ScopeSelector?@argv;state:ApprovalState?@argv;page_size:PageSize?@argv;cursor:Cursor?@argv;all:Bool?@local" },
    Reg { command_key: "approval-show", input_schema: "in-approval-show-v1", target_schema: "tgt-approval-v1", kind: "Q", output_schema: "out-approval-v1", security_class: "read", wait_default: "immediate", wait_allowed: "immediate", typed_fields: "approval:ApprovalSelector!@argv{canonical-id-or-operation}" },
    Reg { command_key: "approval-approve", input_schema: "in-approval-approve-v1", target_schema: "tgt-approval-revision-v1", kind: "C", output_schema: "out-operation-v1", security_class: "security-decision", wait_default: "committed", wait_allowed: "accepted,committed", typed_fields: "approval:ApprovalSelector!@argv{canonical-id-or-operation};if_revision:Revision?@argv" },
    Reg { command_key: "approval-deny", input_schema: "in-approval-deny-v1", target_schema: "tgt-approval-revision-v1", kind: "C", output_schema: "out-operation-v1", security_class: "security-decision", wait_default: "committed", wait_allowed: "accepted,committed", typed_fields: "approval:ApprovalSelector!@argv{canonical-id-or-operation};if_revision:Revision?@argv;reason:BoundedText?@argv" },
    Reg { command_key: "provider-list", input_schema: "in-provider-list-v1", target_schema: "tgt-instance-v1", kind: "Q", output_schema: "out-provider-page-v1", security_class: "read", wait_default: "immediate", wait_allowed: "immediate", typed_fields: "capability:CapabilityId?@argv;page_size:PageSize?@argv;cursor:Cursor?@argv;all:Bool?@local" },
    Reg { command_key: "provider-show", input_schema: "in-provider-show-v1", target_schema: "tgt-provider-generation-v1", kind: "Q", output_schema: "out-provider-v1", security_class: "read", wait_default: "immediate", wait_allowed: "immediate", typed_fields: "provider:ProviderSelector!@argv{canonical-id-or-exact};if_generation:Generation?@argv" },
    Reg { command_key: "side-effect-reconcile", input_schema: "in-side-effect-reconcile-v1", target_schema: "tgt-side-effect-revision-v1", kind: "C", output_schema: "out-operation-v1", security_class: "high-risk", wait_default: "committed", wait_allowed: "accepted,committed", typed_fields: "side_effect:SideEffectSelector!@argv{canonical-id-or-operation};if_revision:Revision?@argv;action:ReconcileAction!@argv{confirm,fail,manual};evidence:EvidenceRef+@argv" },
];